teleop_twist_joy_node:
  ros__parameters:
    axis_linear:
      x: 1
    scale_linear:
      x: 3.0
    scale_linear_turbo:
      x: 5.0

    axis_angular:
      yaw: 0
    scale_angular:
      yaw: 1.07 # -30 to 30 degree

    enable_button: 4  #  LB shoulder button
    enable_turbo_button: 5  # RB shoulder button